#
# Dockerfile to demonstrate the simplest build
#

FROM python

MAINTAINER "Docker Build Lab" <dockerlabs@mjbright.net>

# NOTE: all RUN commands are executed at build time,
# look at the output of the "docker build" below and you will see
# the Python version.

RUN python ‐‐version

CMD bash

